python_luiz_otavio/agenda/contact/urls.py
# type: ignore
from contact import views
from django.urls import path

app_name = 'contact'

urlpatterns = [
    path("search/", views.search, name="search"),
    path("", views.index, name="index"),

    # Contact
    path("contact/<int:contact_id>/detail", views.contact, name="contact"),
    path("contact/create/", views.create, name="create"),
]

python_luiz_otavio/agenda/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("contact.urls")),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

python_luiz_otavio/agenda/contact/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


# Create your models here.
class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return f"{self.name}"


class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=100, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, blank=True, null=True)
    owner = models.ForeignKey(
        User, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"

python_luiz_otavio/agenda/contact/forms.py
from django import forms
from django.core.exceptions import ValidationError
from . import models


class ContactForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "classe-a",
                "placeholder": "Aqui veio do init",
            }
        ),
        label="primeiro nome",
        help_text="Texto de ajuda para seu usuário",
    )

    class Meta:
        model = models.Contact
        fields = (
            "first_name",
            "last_name",
            "phone",
        )
        widgets = {
            "first_name": forms.TextInput(
                attrs={"placeholder": "Escreva seu primeiro nome"}
            )
        }

    def clean(self):
        # cleaned_data = self.cleaned_data
        self.add_error(None, ValidationError("Mensagem de erro", code="invalid"))
        self.add_error(None, ValidationError("Mensagem de erro", code="invalid"))
        self.add_error(None, ValidationError("Mensagem de erro", code="invalid"))
        return super().clean()

python_luiz_otavio/agenda/contact/views/contact_forms.py
# flake8: noqa
from django.shortcuts import render
from contact.forms import ContactForm


def create(request):
    if request.method == "POST":
        context = {"forms": ContactForm(request.POST)}
        return render(request, "contact/create.html", context)
    context = {"form": ContactForm()}
    return render(
        request,
        "contact/create.html",
    )

python_luiz_otavio/agenda/contact/views/contact_views.py
# flake8: noqa
from contact.models import Contact
from django.core.paginator import Paginator
from django.db.models import Q
# from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render


def index(request):
    contacts = Contact.objects \
        .filter(show=True) \
        .order_by('-id')

    paginator = Paginator(contacts, 25)  # Show 25 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Contatos'
    }
    return render(
        request,
        'contact/index.html',
        context
    )


def search(request):
    # strip remove espaço do começo e fim
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect("contact:index")
    contacts = Contact.objects \
        .filter(show=True) \
        .filter(
            Q(first_name__icontains=search_value) |
            Q(last_name__icontains=search_value)
        )\
        .order_by('-id')

    paginator = Paginator(contacts, 25)  # Show 25 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Contatos'
    }
    return render(
        request,
        'contact/index.html',
        context
    )


def contact(request, contact_id):

    single_contact = get_object_or_404(Contact, pk=contact_id, show=True)
    # single_contact = Contact.objects.filter(pk=contact_id).first()

    # if single_contact is None:
    #     raise Http404
    contact_name = f'{single_contact.first_name} {single_contact.last_name}'
    context = {
        'contact': single_contact,
        'site_title': contact_name
    }
    return render(
        request,
        'contact/contact.html',
        context
    )

python_luiz_otavio/agenda/contact/templates/contact/contact.html
{% extends 'global/base.html' %}

{% block content %}
<div class="single-contact">
    <h1 class="single-contact-name">
        {{contact.first_name}} {{contact.last_name}}
    </h1>

    <p><b>ID:</b> {{contact.id}} </p>
    <p><b>EMAIL:</b> {{contact.email}} </p>
    <p><b>PHONE:</b> {{contact.phone}} </p>
    <p><b>CATEGORY:</b> {{contact.category.name}} </p>
    <p><b>DESCRIPTION:</b> {{contact.description}} </p>
    <p><b>CREATED DATE:</b> {{contact.created_date}} </p>
</div>
{% endblock content %}

python_luiz_otavio/agenda/contact/templates/contact/create.html
{% extends 'global/base.html' %}

{% block content %}
    <div class="form-wrapper">

        <h2>Contact</h2>

        <form 
        action="{% url 'contact:create' %}"
        method="POST"
        enctype="multipart/form-data"
        >
        {% csrf_token %}
        <div class="form-content">
            {% for fields in forms  %}
            <div class="form-group">
                <label for="{{fields.id_for_label}}">{{fields.label}}</label>
                {{fields}}

                {{fields.errors}}

                {% if fields.help_text %}
                
                <p class="help-text">
                {{ fields.help_text}}
                </p>
                {% endif %}
            </div>
            {% endfor %}
        </div>

        {% if form.non_field_errors %}
          
            <div class="form-content">
                <div class="form-group">
                    <div class="message error">
                        {{form.non_field_errors}}
                    </div>
                </div>
            </div>
        {% endif %}

        <div class="form-content">
            <div class="form-group">
            <button class="btn" type="submit">Send</button>
            </div>
        </div>

        </form>
    </div>
{% endblock content %}

python_luiz_otavio/agenda/contact/templates/contact/index.html
{% extends 'global/base.html' %} 
{% block content %} 
{% if page_obj %}
 <div class="responsive-table">
  <table class="contacts-table">
    <caption class="table-caption">
      Contacts
    </caption>
    <thead>
      <tr class="table-row table-row-header">
        <th class="table-header">ID</th>
        <th class="table-header">First Name</th>
        <th class="table-header">Last Name</th>
        <th class="table-header">Phone</th>
        <th class="table-header">Email</th>
      </tr>
    </thead>
    <tbody>
      {% for contact in page_obj %} 
      <tr class="table-row">
        <td class="table-cel">
          <a href="{% url 'contact:contact' contact.id %} " class="table-link">
            {{ contact.id }} <br />
          </a>
          <td class="table-cel">
          {{ contact.first_name }} <br />
          <td class="table-cel">
          {{ contact.last_name }} <br />
          <td class="table-cel">
          {{ contact.phone }} <br />
          <td class="table-cel">
          {{ contact.email }} <br />
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
 </div>
 {% else %}
  <div class="single-contact">
    <h1 class="single-contact-name">
      Nenhum contato encontrado
    </h1>
  </div>
 {% endif %}

{% endblock content %}